---
# Title: WeKan - Open-Source Kanban
# 
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/main.yml
#
# Description:
#   Role for provisioning an WeKan server
#   with docker.
#
- name: 

- name: "Pull an (latest) docker image from wekanteam/wekan"
  community.docker.docker_image:
    name: wekanteam/wekan:latest
    source: pull
